# Generated by Django 4.2.11 on 2024-04-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_alter_movies_release'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='poster',
            field=models.CharField(max_length=255000000),
        ),
    ]
