# Generated by Django 4.2.11 on 2024-04-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0013_alter_movies_created_at_alter_movies_release_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='poster',
            field=models.TextField(),
        ),
    ]
