# Generated by Django 4.2.11 on 2024-04-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0015_alter_movies_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='trailer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
